<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="obj\Debug\net7.0\.NETCoreApp,Version=v7.0.AssemblyAttributes.cs" />
    <Compile Include="obj\Debug\net7.0\SchemaCraftHub.AssemblyInfo.cs" />
    <Compile Include="obj\Debug\net7.0\SchemaCraftHub.GlobalUsings.g.cs" />
    <Compile Include="obj\Debug\net7.0\SchemaCraftHub.MvcApplicationPartsAssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="obj\Debug\net7.0\SchemaCraftHub.csproj.FileListAbsolute.txt" />
    <Content Include="obj\Debug\net7.0\SchemaCraftHub.sourcelink.json" />
    <Content Include="obj\Debug\net7.0\staticwebassets.build.json" />
    <Content Include="obj\project.assets.json" />
    <Content Include="obj\SchemaCraftHub.csproj.nuget.dgspec.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="obj\Debug\net7.0\apphost.exe" />
    <None Include="obj\Debug\net7.0\refint\SchemaCraftHub.dll" />
    <None Include="obj\Debug\net7.0\ref\SchemaCraftHub.dll" />
    <None Include="obj\Debug\net7.0\SchemaCr.FDF7D9C9.Up2Date" />
    <None Include="obj\Debug\net7.0\SchemaCraftHub.AssemblyInfoInputs.cache" />
    <None Include="obj\Debug\net7.0\SchemaCraftHub.assets.cache" />
    <None Include="obj\Debug\net7.0\SchemaCraftHub.csproj.AssemblyReference.cache" />
    <None Include="obj\Debug\net7.0\SchemaCraftHub.csproj.BuildWithSkipAnalyzers" />
    <None Include="obj\Debug\net7.0\SchemaCraftHub.csproj.CoreCompileInputs.cache" />
    <None Include="obj\Debug\net7.0\SchemaCraftHub.dll" />
    <None Include="obj\Debug\net7.0\SchemaCraftHub.GeneratedMSBuildEditorConfig.editorconfig" />
    <None Include="obj\Debug\net7.0\SchemaCraftHub.genruntimeconfig.cache" />
    <None Include="obj\Debug\net7.0\SchemaCraftHub.MvcApplicationPartsAssemblyInfo.cache" />
    <None Include="obj\Debug\net7.0\SchemaCraftHub.pdb" />
    <None Include="obj\Debug\net7.0\staticwebassets\msbuild.build.SchemaCraftHub.props" />
    <None Include="obj\Debug\net7.0\staticwebassets\msbuild.buildMultiTargeting.SchemaCraftHub.props" />
    <None Include="obj\Debug\net7.0\staticwebassets\msbuild.buildTransitive.SchemaCraftHub.props" />
    <None Include="obj\project.nuget.cache" />
    <None Include="obj\SchemaCraftHub.csproj.nuget.g.props" />
    <None Include="obj\SchemaCraftHub.csproj.nuget.g.targets" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.7.304.4" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.7.301" />
    <PackageReference Include="EPPlus" Version="7.3.1" />
    <PackageReference Include="InfluxDB.Client" Version="4.17.0" />
    <PackageReference Include="InfluxDB.Client.Core" Version="4.17.0" />
    <PackageReference Include="Cassandra.NET" Version="1.0.7" />
    <PackageReference Include="CassandraCSharpDriver" Version="3.20.1" />
    <PackageReference Include="CqlSharp" Version="0.41.1" />
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="7.0.4" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Npgsql" Version="7.0.7" />
	
	  <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="7.0.4" />
	
	  <PackageReference Include="System.IO.Ports" Version="8.0.0" />
	
	  <PackageReference Include="System.Security.Cryptography.Cng" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClientSchemaHub\ClientSchemaHub.csproj" />
    <ProjectReference Include="..\DBUtilityHub\DBUtilityHub.csproj" />
  </ItemGroup>

</Project>
